# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: x.x.x.$(Rev:r)

trigger:
- master

pool: Self hosted pool

jobs:
  - job: Update_Version
    displayName: Update CI Build Version
    steps:
      - checkout: self
      - task: PowerShell@2
        inputs:
          targetType: "inline"
          script: |
            $version = (Get-Content $(Pipeline.Workspace)/s/package.json) -join "`n" | ConvertFrom-Json | Select -ExpandProperty "version"
            Write-Host Found version: $version in package.json. 
            Write-Host CI build number $(Build.BuildNumber)
            $version = "$(Build.BuildNumber)" -replace "x.x.x", "$version"
            Write-Host Combining package.json version number and CI build number to: $version
            Write-Host "##vso[build.updatebuildnumber]$version"
